import type { BrokerCatalogItem } from "@/types/import";

export type { BrokerCatalogItem };

export const BROKER_CATALOG: BrokerCatalogItem[] = [
  // Crypto
  {
    id: "hyperliquid",
    name: "Hyperliquid",
    category: "crypto",
    icon: "hyperliquid.png",
    status: "active",
    subtitle: "Perpetual DEX",
  },
  {
    id: "binance",
    name: "Binance",
    category: "crypto",
    icon: "binance.svg",
    status: "active",
    subtitle: "Spot & Futures API",
  },
  {
    id: "kraken",
    name: "Kraken",
    category: "crypto",
    icon: "kraken.svg",
    status: "active",
    subtitle: "Spot & Margin API",
  },
  {
    id: "bybit",
    name: "Bybit",
    category: "crypto",
    icon: "bybit.svg",
    status: "active",
    subtitle: "Unified Account API",
    invertInDark: true,
  },
  {
    id: "okx",
    name: "OKX",
    category: "crypto",
    icon: "okx.svg",
    status: "active",
    subtitle: "API v5 Sync",
    invertInDark: true,
  },
  {
    id: "crypto-com",
    name: "Crypto.com",
    category: "crypto",
    icon: "cryptocom.svg",
    status: "active",
    subtitle: "Exchange API",
  },

  // Stocks & Options
  {
    id: "alpaca",
    name: "Alpaca",
    category: "stocks",
    icon: "alpaca.svg",
    status: "active",
    subtitle: "Commission-free API",
  },
  {
    id: "public",
    name: "Public",
    category: "stocks",
    icon: "public.svg",
    status: "active",
    subtitle: "Stocks & ETFs",
  },
  {
    id: "webull",
    name: "Webull",
    category: "stocks",
    icon: "webull.svg",
    status: "active",
    subtitle: "Open API Sync",
  },
  {
    id: "tradier",
    name: "Tradier",
    category: "stocks",
    icon: "tradier.svg",
    status: "active",
    subtitle: "Equities & Options API",
  },
  {
    id: "questrade",
    name: "Questrade",
    category: "stocks",
    icon: "questrade.svg",
    status: "active",
    subtitle: "API Sync",
    invertInDark: true,
  },
  {
    id: "trading212",
    name: "Trading 212",
    category: "stocks",
    icon: "trading212.png",
    status: "active",
    subtitle: "Zero-Commission Investing",
  },
  {
    id: "ibkr-flex",
    name: "Interactive Brokers",
    category: "stocks",
    icon: "ibkr.svg",
    status: "active",
    subtitle: "Flex Query & Web API",
  },
  {
    id: "etrade",
    name: "E*TRADE",
    category: "stocks",
    icon: "etrade.png",
    status: "soon",
    subtitle: "Soon · CSV import today",
  },
  {
    id: "tastytrade",
    name: "tastytrade",
    category: "stocks",
    icon: "tastytrade.svg",
    status: "soon",
    subtitle: "Soon · CSV import today",
  },
  {
    id: "tradestation",
    name: "TradeStation",
    category: "stocks",
    icon: "tradestation.svg",
    status: "soon",
    subtitle: "Soon · CSV import today",
  },
  {
    id: "schwab",
    name: "Charles Schwab",
    category: "stocks",
    icon: "schwab.png",
    status: "soon",
    subtitle: "Soon · CSV import today",
  },

  // Futures & Prop Trading
  {
    id: "ftmo",
    name: "FTMO",
    category: "futures",
    icon: "ftmo.png",
    status: "active",
    subtitle: "MetaTrader & cTrader",
    invertInDark: true,
  },
  {
    id: "topstep",
    name: "Topstep",
    category: "futures",
    icon: "topstep.jpg",
    status: "active",
    subtitle: "TopstepX API sync",
  },
  {
    id: "tradovate",
    name: "Tradovate",
    category: "futures",
    icon: "tradovate.svg",
    status: "soon",
    subtitle: "Soon · CSV import today",
  },
  {
    id: "ninjatrader",
    name: "NinjaTrader",
    category: "futures",
    icon: "ninjatrader.svg",
    status: "soon",
    subtitle: "Soon · CSV import today",
  },
];
